# Generated by Django 2.2.9 on 2020-02-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=200)),
                ('orglist', models.CharField(max_length=200)),
                ('networklist', models.CharField(max_length=200)),
                ('permisson', models.CharField(max_length=200)),
            ],
        ),
    ]
