# Generated by Django 2.2.10 on 2020-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=200)),
                ('networkname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('gw', models.CharField(max_length=200)),
                ('mask', models.CharField(max_length=200)),
                ('dns1', models.CharField(max_length=200)),
                ('dns2', models.CharField(max_length=200)),
                ('vlan', models.CharField(max_length=200)),
                ('nettags', models.CharField(max_length=200)),
            ],
        ),
    ]
