# Generated by Django 2.2.10 on 2020-02-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0002_csv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSV',
            new_name='bulk',
        ),
    ]
