# Generated by Django 2.2.10 on 2020-04-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0005_auto_20200206_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulk',
            name='submissionID',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
