# Generated by Django 2.2.10 on 2020-04-22 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0010_auto_20200422_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtable',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
