# Generated by Django 2.2.10 on 2020-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0014_subtable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtable',
            name='subtype',
            field=models.CharField(choices=[('addDev', 'addDev'), ('backupDev', 'backupDev'), ('vlan', 'vlan'), ('switch', 'switch'), ('mxPort', 'mxPort')], max_length=10),
        ),
    ]
