# Generated by Django 2.2.12 on 2020-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0017_auto_20200423_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='number',
            field=models.IntegerField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtable',
            name='subtype',
            field=models.CharField(choices=[('addDev', 'addDev'), ('backupDev', 'backupDev'), ('backupOrg', 'backupORG')], max_length=10),
        ),
    ]
