# Generated by Django 2.2.12 on 2020-04-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0018_auto_20200424_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='number',
            field=models.IntegerField(),
        ),
    ]
