# Generated by Django 2.2.12 on 2020-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0019_auto_20200424_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='serial',
            field=models.CharField(max_length=16),
        ),
    ]
